
import './globals.css'
import type { Metadata } from 'next'
import { Sidebar } from './components/Sidebar'
export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}
export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <head>
        <link
          href="https://fonts.googleapis.com/css2?family=Poppins:wght@400;500;600;700&family=Amaranth:wght@400;700&family=Inria+Sans:wght@400;700&family=Kumbh+Sans:wght@400;700&display=swap"
          rel="stylesheet"
        />
        <style>
          {`
            body {
              display: flex;
            }
            .content {
              flex: 1; /* Take up remaining space */
              padding: 20px; /* Add padding for the content */
            }
           
          `}
        </style>
      </head>
      <body>
        <div>
          <Sidebar />
        </div>
        <div className="content">
          {children}
        </div>
      </body>
    </html>
  )
}